"""change social_network field to list of dict

Revision ID: d34da86f022f
Revises: 5b62773a75e4
Create Date: 2024-09-06 15:13:47.902222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd34da86f022f'
down_revision: Union[str, None] = '5b62773a75e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_personal_address', table_name='personal')
    op.drop_index('ix_personal_birth_date', table_name='personal')
    op.drop_index('ix_personal_email', table_name='personal')
    op.drop_index('ix_personal_fathername', table_name='personal')
    op.drop_index('ix_personal_id', table_name='personal')
    op.drop_index('ix_personal_main_image', table_name='personal')
    op.drop_index('ix_personal_name', table_name='personal')
    op.drop_index('ix_personal_phone_number', table_name='personal')
    op.drop_index('ix_personal_surname', table_name='personal')
    op.drop_table('personal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('fathername', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('social_network', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birth_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('main_image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='personal_pkey')
    )
    op.create_index('ix_personal_surname', 'personal', ['surname'], unique=False)
    op.create_index('ix_personal_phone_number', 'personal', ['phone_number'], unique=False)
    op.create_index('ix_personal_name', 'personal', ['name'], unique=False)
    op.create_index('ix_personal_main_image', 'personal', ['main_image'], unique=False)
    op.create_index('ix_personal_id', 'personal', ['id'], unique=False)
    op.create_index('ix_personal_fathername', 'personal', ['fathername'], unique=False)
    op.create_index('ix_personal_email', 'personal', ['email'], unique=False)
    op.create_index('ix_personal_birth_date', 'personal', ['birth_date'], unique=False)
    op.create_index('ix_personal_address', 'personal', ['address'], unique=False)
    # ### end Alembic commands ###
